### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by jammersonf** [stonkeep/clicksign#2]
Mano, sabe pq só me retorna 403 forbidden?

já peguei o token de sandbox, de produção e nada.
![image](https://user-images.githubusercontent.com/2231447/146257480-b760ab88-ff20-48f7-9d56-d5d8a9ee2ee4.png)

Pelo que vi, tá tudo sendo passado certinho
![image](https://user-images.githubusercontent.com/2231447/146257571-d35cce87-ff9a-464d-8490-fe3069c4fe4f.png)

**Comment by mateusgalasso** [comment]
403 normalmente é que vc não tem acesso, colocou a chave da API corretamente?Só se a clicksign alterou alguma coisa e eu não estou sabendovou pesquisar
   Em quarta-feira, 15 de dezembro de 2021 17:08:24 BRT, Jammerson Fernando ***@***.***> escreveu:  
 
 


Mano, sabe pq só me retorna 403 forbidden?

já peguei o token de sandbox, de produção e nada.


Pelo que vi, tá tudo sendo passado certinho


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jammersonf** [comment]
EU vi lá, é pq eu não tinha selecionado o usuário la da api
